### ISSUE TITLE
ReferenceError: defaultModes is not defined

### ISSUE THREAD

**Issue by lcherone** [mathieutu/vue-cli-plugin-express#15]
When testing this plugin on a fresh empty default project created with vue ui, it fails to finish install and does not work.

Creates a folder called `undefined`, with the `index.js` in.

And running the tasks fail, most likely todo with the failed installation.

```
$ vue-cli-service express:watch
/home/*/Desktop/Workspaces/*/node_modules/esm/esm.js:1
const __global__ = this;(function (require, module, __shared__) { var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,function(){return e}},r(r.s=2)})([(function(e,t){var r;t=e.exports=$,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Number.MAX_SAFE_INTE

/home/*/Desktop/Workspaces/*/node_modules/@vue/cli-service/lib/Service.js:38
ReferenceError: defaultModes is not defined
    at Service.modes.plugins.reduce (/home/*/Desktop/Workspaces/*/node_modules/@vue/cli-service/lib/Service.js:38:57)
    at Array.reduce (<anonymous>)
    at new Service (/home/*/Desktop/Workspaces/*/node_modules/@vue/cli-service/lib/Service.js:38:31)
    at Object.<anonymous> (/home/*/Desktop/Workspaces/*/node_modules/@vue/cli-service/bin/vue-cli-service.js:16:17)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)

Total task duration: 1.43s
```

**Sidenote:** It baffles me as to why so much effort and over-engineering goes into basically changing a javascript object

```
module.exports = {
  ...
  pluginOptions: {
    express: {
      shouldServeApp: undefined,
      serverDir: undefined
    }
  }
}
```

and creating a folder and putting a file in it :/

What's the point of this plugin, over just `npm install express`?

**Comment by krogla** [comment]
+1

**Comment by mathieutu** [comment]
Hi folks, I'm just seeing this issue. Sorry, but I should really have a problem with github notifications.

I think this is because some Vue CLI api changes, last time I used the plugin, it worked perfectly.

I'm trying to fix that right now.

**Comment by mathieutu** [comment]
And for the point of the plugin, it's not just creating file and installing express. It handles all the server for you.

**Comment by mathieutu** [comment]
Hi, this is linked to #14, so I'm closing this one to put all in one place.
